.TH "C:/Users/Peter/Documents/Arduino/libraries/SODA/SODA.h" 3 "Sun Jun 28 2015" "SODA Arudino library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/Peter/Documents/Arduino/libraries/SODA/SODA.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <Arduino\&.h>\fP
.br
\fC#include <Wire\&.h>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBSODA\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBFILENAME\fP   'DATA\&.CSV'"
.br
.ti -1c
.RI "#define \fBCLOCK_I2C_ADDR\fP   0x68"
.br
.ti -1c
.RI "#define \fBCLOCK_CONTROL_ADDR\fP   0x0E"
.br
.ti -1c
.RI "#define \fBCLOCK_TEMPERATURE_ADDR\fP   0x11"
.br
.ti -1c
.RI "#define \fBCLOCK_TIME_CAL_ADDR\fP   0x00"
.br
.ti -1c
.RI "#define \fBCLOCK_SETUP\fP   0x5"
.br
.ti -1c
.RI "#define \fBCLOCK_ALARM1_ADDR\fP   0x07"
.br
.ti -1c
.RI "#define \fBCLOCK_ALARM_STATUS\fP   0x0F"
.br
.ti -1c
.RI "#define \fBADC_I2C_ADDR\fP   0x6E"
.br
.ti -1c
.RI "#define \fBADC_CONTROL\fP   0x00"
.br
.ti -1c
.RI "#define \fBADC_BASE\fP   0x80"
.br
.ti -1c
.RI "#define \fBADC_CH1\fP   0x00"
.br
.ti -1c
.RI "#define \fBADC_CH2\fP   0x20"
.br
.ti -1c
.RI "#define \fBADC_CH3\fP   0x40"
.br
.ti -1c
.RI "#define \fBADC_CH4\fP   0x60"
.br
.ti -1c
.RI "#define \fBADC_18BITS\fP   0x0C"
.br
.ti -1c
.RI "#define \fBADC_16BITS\fP   0x08"
.br
.ti -1c
.RI "#define \fBADC_14BITS\fP   0x04"
.br
.ti -1c
.RI "#define \fBADC_12BITS\fP   0x00"
.br
.ti -1c
.RI "#define \fBADC_GAIN1\fP   0x00"
.br
.ti -1c
.RI "#define \fBADC_GAIN2\fP   0x01"
.br
.ti -1c
.RI "#define \fBADC_GAIN4\fP   0x02"
.br
.ti -1c
.RI "#define \fBADC_GAIN8\fP   0x03"
.br
.ti -1c
.RI "#define \fBLEDPIN\fP   13"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define ADC_12BITS   0x00"

.SS "#define ADC_14BITS   0x04"

.SS "#define ADC_16BITS   0x08"

.SS "#define ADC_18BITS   0x0C"

.SS "#define ADC_BASE   0x80"

.SS "#define ADC_CH1   0x00"

.SS "#define ADC_CH2   0x20"

.SS "#define ADC_CH3   0x40"

.SS "#define ADC_CH4   0x60"

.SS "#define ADC_CONTROL   0x00"

.SS "#define ADC_GAIN1   0x00"

.SS "#define ADC_GAIN2   0x01"

.SS "#define ADC_GAIN4   0x02"

.SS "#define ADC_GAIN8   0x03"

.SS "#define ADC_I2C_ADDR   0x6E"

.SS "#define CLOCK_ALARM1_ADDR   0x07"

.SS "#define CLOCK_ALARM_STATUS   0x0F"

.SS "#define CLOCK_CONTROL_ADDR   0x0E"

.SS "#define CLOCK_I2C_ADDR   0x68"

.SS "#define CLOCK_SETUP   0x5"

.SS "#define CLOCK_TEMPERATURE_ADDR   0x11"

.SS "#define CLOCK_TIME_CAL_ADDR   0x00"

.SS "#define FILENAME   'DATA\&.CSV'"

.SS "#define LEDPIN   13"

.SH "Author"
.PP 
Generated automatically by Doxygen for SODA Arudino library from the source code\&.
