.TH "C:/Users/Peter/Documents/Arduino/libraries/SODA/SODA.cpp" 3 "Sun Jun 28 2015" "SODA Arudino library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/Peter/Documents/Arduino/libraries/SODA/SODA.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'Arduino\&.h'\fP
.br
\fC#include <EEPROM\&.h>\fP
.br
\fC#include 'SODA\&.h'\fP
.br
\fC#include <SdFat\&.h>\fP
.br

.SS "Variables"

.in +1c
.ti -1c
.RI "SdFat \fBcard\fP"
.br
.ti -1c
.RI "SdFile \fBfile\fP"
.br
.ti -1c
.RI "int \fBtimeArray\fP [6] = {2010,1,1,12,0,0}"
.br
.ti -1c
.RI "char \fBbuffer\fP [30]"
.br
.ti -1c
.RI "int \fBbufferIndex\fP = 0"
.br
.ti -1c
.RI "boolean \fBend_on_connect\fP = false"
.br
.ti -1c
.RI "boolean \fBsingle_file\fP = false"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "char buffer[30]"

.SS "int bufferIndex = 0"

.SS "SdFat card"

.SS "boolean end_on_connect = false"

.SS "SdFile file"

.SS "boolean single_file = false"

.SS "int timeArray[6] = {2010,1,1,12,0,0}"

.SH "Author"
.PP 
Generated automatically by Doxygen for SODA Arudino library from the source code\&.
